/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labreso.view;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import labreso.controller.Client;
import labreso.controller.DataReceiver;

/**
 *Tela do jogo 
 * @author 940437
 */
public class GameView extends javax.swing.JFrame implements DataReceiver.ClientListener {
    
    private Thread thread;
    private Client client;
    private boolean gameStarted;
    private boolean userPlayed;
    private String userName;
    private String[] opponents;
    private String[] actions;
    private boolean allPlayersLoaded;
    /**
     * Creates new form GameView
     */
    GameView(String host, int port, String name) {
        userName = name;
        client = new Client(host, port, name, this);
        thread = new Thread(() -> {
            client.initClient();
        });
        thread.start();
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelWaitMsg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelUserOption = new javax.swing.JLabel();
        labelOne = new javax.swing.JLabel();
        labelTwo = new javax.swing.JLabel();
        labelOpponent2Option = new javax.swing.JLabel();
        labelOppontent1Option = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelOpponent1 = new javax.swing.JLabel();
        labelOpponent2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 1991, -1, -1));

        labelWaitMsg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelWaitMsg.setText("Aguardando Jogadores...");
        getContentPane().add(labelWaitMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/grab-vector-graphic-person-icon--imagebasket-13.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 295, 249));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/grab-vector-graphic-person-icon--imagebasket-13.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 295, 249));

        labelUserOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/two.png"))); // NOI18N
        getContentPane().add(labelUserOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        labelOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/one.png"))); // NOI18N
        labelOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOneMouseClicked(evt);
            }
        });
        getContentPane().add(labelOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        labelTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/two.png"))); // NOI18N
        labelTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTwoMouseClicked(evt);
            }
        });
        getContentPane().add(labelTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 720, -1, -1));

        labelOpponent2Option.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/two.png"))); // NOI18N
        getContentPane().add(labelOpponent2Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        labelOppontent1Option.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labreso/two.png"))); // NOI18N
        getContentPane().add(labelOppontent1Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("<<<<Escolha uma das opções>>>>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 730, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1080, 10));

        labelOpponent1.setText("Aguardando...");
        getContentPane().add(labelOpponent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        labelOpponent2.setText("Aguardando...");
        getContentPane().add(labelOpponent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOneMouseClicked
        sendCommand("One");
    }//GEN-LAST:event_labelOneMouseClicked

    private void sendCommand(String command) {
        if ((gameStarted && allPlayersLoaded )&& !userPlayed) {
            changeUserIcon(labelUserOption, command);
            userPlayed = true;
            client.sendMessageToServer(command);
        } else if (!gameStarted || !allPlayersLoaded) {
            JOptionPane.showMessageDialog(rootPane, "Aguarde os outros jogadores!");
        } else if (userPlayed) {
            JOptionPane.showMessageDialog(rootPane, "Você ja realizou sua joagada, aguarde o resultado!");
        }
    }
    private void labelTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTwoMouseClicked
        sendCommand("Two");
    }//GEN-LAST:event_labelTwoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelOne;
    private javax.swing.JLabel labelOpponent1;
    private javax.swing.JLabel labelOpponent2;
    private javax.swing.JLabel labelOpponent2Option;
    private javax.swing.JLabel labelOppontent1Option;
    private javax.swing.JLabel labelTwo;
    private javax.swing.JLabel labelUserOption;
    private javax.swing.JLabel labelWaitMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onGameStarted() {
        gameStarted = true;
        labelWaitMsg.setVisible(false);
    }

    @Override
    public void onDraw() {
        userPlayed = false;
        changeUserIcon(labelOppontent1Option, actions[0]);
        changeUserIcon(labelOpponent2Option, actions[1]);
        JOptionPane.showMessageDialog(rootPane, "Houve empate!");
    }

    private void changeUserIcon(JLabel label, String command) {
        label.setIcon(
                new ImageIcon(getClass()
                        .getResource(
                                command.equals("One")
                                ? "/labreso/one.png"
                                : "/labreso/two.png")
                ));
    }

    @Override
    public void onGetPlayers(String[] players) {
        System.out.println(Arrays.toString(players));
        actions = new String[players.length - 1];
        opponents = new String[players.length - 1];
        int count = 0;
        for (String s : players) {
            if (!s.equals(userName)) {
                opponents[count] = s;
                count++;
            }
        }
        allPlayersLoaded = true;
        fillOpponentsData();
    }

    @Override
    public void onActionReceived(String player, String action) {
        if (player.equals(opponents[0])) {
            actions[0] = action;
        } else if (player.equals(opponents[1])) {
            actions[1] = action;
        }
    }

    @Override
    public void onResultWinner(String winner) {
        userPlayed = false;
        changeUserIcon(labelOppontent1Option, actions[0]);
        changeUserIcon(labelOpponent2Option, actions[1]);
        if (winner.equals(userName)) {
            JOptionPane.showMessageDialog(rootPane, "Voce venceu!");
        } else {
            JOptionPane.showMessageDialog(rootPane, winner + " venceu!");
        }
    }

    private void fillOpponentsData() {
        labelOpponent1.setText(opponents[0]);
        labelOpponent2.setText(opponents[1]);
    }

}
